# Generated by Django 5.0.6 on 2024-05-23 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("lastname", models.CharField(max_length=255)),
                ("firstname", models.CharField(max_length=255)),
                ("middleinitial", models.CharField(max_length=255, null=True)),
                ("ranks", models.CharField(max_length=50)),
                ("assignment_level", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
